package data_analysis.rake;

public class RakeLanguages {
    public static String ARABIC = "ar";
    public static String ARMENIAN = "hy";
    public static String BASQUE = "eu";
    public static String BENGALI = "bn";
    public static String BULGARIAN = "bg";
    public static String CATALAN = "ca";
    public static String CHINESE_PRC = "zh_cn";
    public static String CHINESE_TAIWAN = "zh_tw";
    public static String CROATIAN = "hr";
    public static String CZECH = "cs";
    public static String DANISH = "da";
    public static String DUTCH = "nl";
    public static String ENGLISH = "en";
    public static String FINNISH = "fi";
    public static String FRENCH = "fr";
    public static String GALICIAN = "gl";
    public static String GERMAN = "de";
    public static String GREEK = "el";
    public static String HEBREW = "he";
    public static String HINDU = "hi";
    public static String HUNGARIAN = "hu";
    public static String INDONESIAN = "id";
    public static String IRISH = "ga";
    public static String ITALIAN = "it";
    public static String JAPANESE = "ja";
    public static String KOREAN = "ko";
    public static String KURDISH = "ku";
    public static String LATVIAN = "lv";
    public static String LITHUANIAN = "lt";
    public static String MARATHI = "mr";
    public static String NORSK = "no";
    public static String PERSIAN = "fa";
    public static String POLISH = "pl";
    public static String PORTUGUESE = "pt";
    public static String PORTUGUESE_BRAZIL = "pt_br";
    public static String ROMANIAN = "ro";
    public static String RUSSIAN = "ru";
    public static String SLOVAK = "sk";
    public static String SPANISH = "es";
    public static String SWEDISH = "sv";
    public static String THAI = "th";
    public static String TURKISH = "tr";
    public static String UKRAINIAN = "uk";
    public static String URDU = "ur";
    public static String[] stopWords = {"a",
            "about",
            "above",
            "across",
            "after",
            "again",
            "against",
            "all",
            "almost",
            "alone",
            "along",
            "already",
            "also",
            "although",
            "always",
            "among",
            "an",
            "and",
            "another",
            "any",
            "anybody",
            "anyone",
            "anything",
            "anywhere",
            "are",
            "area",
            "areas",
            "around",
            "as",
            "ask",
            "asked",
            "asking",
            "asks",
            "at",
            "away",
            "b",
            "back",
            "backed",
            "backing",
            "backs",
            "be",
            "because",
            "became",
            "become",
            "becomes",
            "been",
            "before",
            "began",
            "behind",
            "being",
            "beings",
            "best",
            "better",
            "between",
            "big",
            "both",
            "but",
            "by",
            "c",
            "came",
            "can",
            "cannot",
            "case",
            "cases",
            "certain",
            "certainly",
            "clear",
            "clearly",
            "come",
            "could",
            "d",
            "did",
            "differ",
            "different",
            "differently",
            "do",
            "does",
            "done",
            "down",
            "downed",
            "downing",
            "downs",
            "during",
            "e",
            "each",
            "early",
            "either",
            "end",
            "ended",
            "ending",
            "ends",
            "enough",
            "even",
            "evenly",
            "ever",
            "every",
            "everybody",
            "everyone",
            "everything",
            "everywhere",
            "f",
            "face",
            "faces",
            "fact",
            "facts",
            "far",
            "felt",
            "few",
            "find",
            "finds",
            "first",
            "for",
            "four",
            "from",
            "full",
            "fully",
            "further",
            "furthered",
            "furthering",
            "furthers",
            "g",
            "gave",
            "general",
            "generally",
            "get",
            "gets",
            "give",
            "given",
            "gives",
            "go",
            "going",
            "good",
            "goods",
            "got",
            "great",
            "greater",
            "greatest",
            "group",
            "grouped",
            "grouping",
            "groups",
            "h",
            "had",
            "has",
            "have",
            "having",
            "he",
            "her",
            "herself",
            "here",
            "high",
            "higher",
            "highest",
            "him",
            "himself",
            "his",
            "how",
            "however",
            "i",
            "if",
            "important",
            "in",
            "interest",
            "interested",
            "interesting",
            "interests",
            "into",
            "is",
            "it",
            "its",
            "itself",
            "j",
            "just",
            "k",
            "keep",
            "keeps",
            "kind",
            "knew",
            "know",
            "known",
            "knows",
            "l",
            "large",
            "largely",
            "last",
            "later",
            "latest",
            "least",
            "less",
            "let",
            "lets",
            "like",
            "likely",
            "long",
            "longer",
            "longest",
            "m",
            "made",
            "make",
            "making",
            "man",
            "many",
            "may",
            "me",
            "member",
            "members",
            "men",
            "might",
            "more",
            "most",
            "mostly",
            "mr",
            "mrs",
            "much",
            "must",
            "my",
            "myself",
            "n",
            "necessary",
            "need",
            "needed",
            "needing",
            "needs",
            "never",
            "new",
            "newer",
            "newest",
            "next",
            "no",
            "non",
            "not",
            "nobody",
            "noone",
            "nothing",
            "now",
            "nowhere",
            "number",
            "numbered",
            "numbering",
            "numbers",
            "o",
            "of",
            "off",
            "often",
            "old",
            "older",
            "oldest",
            "on",
            "once",
            "one",
            "only",
            "open",
            "opened",
            "opening",
            "opens",
            "or",
            "order",
            "ordered",
            "ordering",
            "orders",
            "other",
            "others",
            "our",
            "out",
            "over",
            "p",
            "part",
            "parted",
            "parting",
            "parts",
            "per",
            "perhaps",
            "place",
            "places",
            "point",
            "pointed",
            "pointing",
            "points",
            "possible",
            "present",
            "presented",
            "presenting",
            "presents",
            "problem",
            "problems",
            "put",
            "puts",
            "q",
            "quite",
            "r",
            "rather",
            "really",
            "right",
            "room",
            "rooms",
            "s",
            "said",
            "same",
            "saw",
            "say",
            "says",
            "second",
            "seconds",
            "see",
            "seem",
            "seemed",
            "seeming",
            "seems",
            "sees",
            "several",
            "shall",
            "she",
            "should",
            "show",
            "showed",
            "showing",
            "shows",
            "side",
            "sides",
            "since",
            "small",
            "smaller",
            "smallest",
            "so",
            "some",
            "somebody",
            "someone",
            "something",
            "somewhere",
            "state",
            "states",
            "still",
            "such",
            "sure",
            "t",
            "take",
            "taken",
            "than",
            "that",
            "the",
            "their",
            "them",
            "then",
            "there",
            "therefore",
            "these",
            "they",
            "thing",
            "things",
            "think",
            "thinks",
            "this",
            "those",
            "though",
            "thought",
            "thoughts",
            "three",
            "through",
            "thus",
            "to",
            "today",
            "together",
            "too",
            "took",
            "toward",
            "turn",
            "turned",
            "turning",
            "turns",
            "two",
            "u",
            "under",
            "until",
            "up",
            "upon",
            "us",
            "use",
            "uses",
            "used",
            "v",
            "very",
            "w",
            "want",
            "wanted",
            "wanting",
            "wants",
            "was",
            "way",
            "ways",
            "we",
            "well",
            "wells",
            "went",
            "were",
            "what",
            "when",
            "where",
            "whether",
            "which",
            "while",
            "who",
            "whole",
            "whose",
            "why",
            "will",
            "with",
            "within",
            "without",
            "work",
            "worked",
            "working",
            "works",
            "would",
            "x",
            "y",
            "year",
            "years",
            "yet",
            "you",
            "young",
            "younger",
            "youngest",
            "your",
            "yours",
            "z"};//https://github.com/aneesha/RAKE/blob/master/FoxStoplist.txt
}
